Update to v1.4: Added KDE GUI outputs
Added -k option to use notify-send and kdialog for output and error
messages.
Added non style option (-s) to disable all output colors. Automatically
enabled when -k option is set.
Change all echo lines to use functions message outputs

diff --git a/force-xdg b/force-xdg
--- a/force-xdg
+++ b/force-xdg
@@ -33,7 +33,7 @@ set -euo pipefail
 #-----------------------------------------------------------------------
 #  Global settings
 #-----------------------------------------------------------------------
-SCRIPT_VERSION="1.3"
+SCRIPT_VERSION="1.4"
 SHORT_DESCRIPTION="A BASH script to force XDG paths for programs polluting HOME."
 SCRIPT_NAME="Force-XDG"
 
@@ -42,6 +42,7 @@ FAKE_HOME_FOLDER="$FORCE_XDG_FOLDER/fake_home"
 
 DEPENDENCIES=( "mapfile" "read" "getopts" "sed" "grep" "diff" "sort"\
                "basename" "readlink" "tput" )
+KDE_DEPENDENCIES=( "kdialog" "notify-send" )
 # Get the real script filename even through a symbolic link
 SCRIPT_RUN="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
 
@@ -61,24 +62,28 @@ F_ARG="\033[1;32m"
 F_OPT="\033[1;32m"
 F_SCR="\033[1;36m\e[1m${SCRIPT_RUN}:${NS} "
 F_WAR="\033[0;33m\e[3m"
+F_SEP="="
 
 
 #-----------------------------------------------------------------------
 # Check dependencies
 #-----------------------------------------------------------------------
-missing_deps=0
-for dependency in "${DEPENDENCIES[@]}"; do
-    if ! command -v "$dependency" > /dev/null 2>&1 ; then
-        echo -e "$F_ERR$SCRIPT_RUN: Could't find '$dependency' on the system."\
-                "Check if is installed.$NS" >&2
-        ((++missing_deps))
+function checkdeps()
+{
+    local missing_deps=0
+    for dependency in "$@"; do
+        if ! command -v "$dependency" > /dev/null 2>&1 ; then
+            echo -e "$SCRIPT_RUN: Could't find '$dependency' on the system."\
+                    "Check if is installed." >&2
+            ((++missing_deps))
+        fi
+    done
+    if [[ $missing_deps -gt 0 ]]; then
+        exit 1
     fi
-done
-if [[ $missing_deps -gt 0 ]]; then
-    exit 1
-fi
+}
 
-
+checkdeps "${DEPENDENCIES[@]}"
 
 #===  FUNCTION  ================================================================
 #         NAME:   Version
@@ -116,10 +121,36 @@ $F_OPT  -c (custom)      ${NS}Change the program identifier to a custom one. Use
 $F_OPT  -d (dir)         ${NS}Manually set ${SCRIPT_NAME} data dir
                    ($ITL$FORCE_XDG_FOLDER$NS by default)
 $F_OPT  -f (fake)        ${NS}Enable fake \$HOME mode.
+$F_OPT  -k (kde)         ${NS}Enable KDE 'kdialog' output mode.
+$F_OPT  -s (no style)    ${NS}Disable style and colors.
 $F_OPT  -h (help)        ${NS}Display this help message.
 $F_OPT  -v (version)     ${NS}Display the version of $SCRIPT_NAME and exit."
 
 }  # ------------  end of function help  ------------
+
+#===  FUNCTION  ================================================================
+#         NAME:   No styles
+#  DESCRIPTION:   Remove output message styles and colors.
+#===============================================================================
+function no_styles()
+{
+    GREEN=""
+    ORANGE=""
+    NS="" # No color
+    BLD=""  # Bold text style
+    ITL=""  # Italic text style
+
+    F_OK="OK"
+    F_APP=""
+    F_ERR=""
+    F_CMD=""
+    F_ARG=""
+    F_OPT=""
+    F_SCR="${SCRIPT_RUN}: "
+    F_WAR=""
+    F_SEP=""
+
+}  # ------------  end of function no_styles  ------------
 
 
 
@@ -140,13 +171,87 @@ app_dirs_and_files=()
 home_before=""
 home_after=""
 
+kde_mode=false
+kde_message=""
+
+
+#===  FUNCTION  ================================================================
+#         NAME:   Error Msg
+#  DESCRIPTION:   Short description.
+#    ARGUMENTS:   $1: Description.
+#===============================================================================
+function error_msg()
+{
+    if [[ $kde_mode == true ]]; then
+        #kdialog --error "$*"
+        notify-send -a "${SCRIPT_NAME}" \
+                    -h "string:desktop-entry:org.kde.konsole" \
+                    --icon=dialog-error \
+                    "Error" "$*"
+    else
+        echo -e "${F_ERR}$SCRIPT_RUN: Error:" "$*" >&2
+    fi
+
+}  # ------------  end of function error_msg  ------------
+function partial_msg()
+{
+    if [[ $kde_mode == true ]]; then
+        kde_message+="${1}"
+    else
+        echo -en "${1}"
+    fi
+}
+function non_gui_message()
+{
+    if [[ $kde_mode == true ]]; then
+        kde_message=""
+    else
+        echo -e "${1}"
+    fi
+}
+function notify_msg()
+{
+    if [[ $kde_mode == true ]]; then
+        kde_message+="$*"
+        notify-send -a "$SCRIPT_NAME" \
+                    -h "string:desktop-entry:org.kde.konsole" \
+                    --icon=dialog-information \
+                    "Output:" "${kde_message}"
+        kde_message=""
+    else
+        echo -e "${1}"
+    fi
+}
+function notify_msg_dont_store()
+{
+    if [[ $kde_mode == true ]]; then
+        kde_message+="$*"
+        notify-send -a "$SCRIPT_NAME" \
+                    --icon=dialog-information \
+                    "Output:" "${kde_message}"
+        kde_message=""
+    else
+        echo -e "${1}"
+    fi
+}
+
+
+
 
 #-------------------------------------------------------------------------------
 #  Handle command line arguments
 #-------------------------------------------------------------------------------
-while getopts ":hvc:d:f" opt
+while getopts ":skhvc:d:f" opt
     do
         case $opt in
+            s)
+                no_styles
+                ;;
+            k)
+                kde_mode=true
+                no_styles
+                checkdeps "${KDE_DEPENDENCIES[@]}"
+                ;;
             h)
                 version
                 help
@@ -166,13 +271,12 @@ while getopts ":hvc:d:f" opt
                 fake_home_mode=true
                 ;;
             :)
-                echo -e "$F_ERR$SCRIPT_NAME: Invalid option: '-$OPTARG'" \
-                        "requires an argument. Check '-help'.$NS" >&2
+                error_msg "Invalid option: '-$OPTARG'" \
+                        "requires an argument. Check '-help'.$NS"
                 exit 1
                 ;;
             *)
-                echo -e "$F_ERR$SCRIPT_NAME: Invalid option: '-$OPTARG'." \
-                        "Check '-help'.$NS" >&2
+                error_msg "Invalid option: '-$OPTARG'. Check '-help'.$NS"
                 exit 1
                 ;;
     esac
@@ -184,8 +288,7 @@ shift $((OPTIND-1))
 
 # Check arguments
 if [[ $# -eq 0 ]]; then
-    echo -e "${F_ERR}$SCRIPT_RUN: Error: Missing arguments." \
-            "Check '${SCRIPT_RUN} -help'.$NS" >&2
+    error_msg "Missing arguments. Check '${SCRIPT_RUN} -help'.$NS"
     exit 1
 fi
 
@@ -199,8 +302,7 @@ fi
 
 # Check if passed app exist on the system
 if ! command -v "$app_name_raw" > /dev/null 2>&1; then
-    echo -e "$F_ERR$SCRIPT_RUN: ERROR: Could't find '$app_name_raw'" \
-            "on the system.$NS" >&1
+    error_msg "Could't find '$app_name_raw' on the system.$NS"
     exit 1
 fi
 
@@ -209,8 +311,7 @@ app_args=("${*:2}")
 
 # Check custom dir and fake_home_mode at the same time
 if [[ -n ${custom_dir} && ${fake_home_mode} == true ]]; then
-    echo -e "$F_ERR$SCRIPT_RUN:" \
-            "ERROR: Can't use custom dir with fake mode enabled.$NS"
+    error_msg "Can't use custom dir with fake mode enabled.$NS"
     exit 1
 # Use custom dir if setted
 elif [[ -n ${custom_dir} ]]; then
@@ -230,12 +331,12 @@ F_APP="${F_APP}${app_name}$NS$ITL"
 #===============================================================================
 function get_dir_and_files_from_db()
 {
-    echo -en "${F_SCR}${ITL}Retrieving data of '${F_APP}' in the db:$NS "
+    partial_msg "${F_SCR}${ITL}Retrieving data of '${F_APP}' in the db:$NS "
     if [[ ! -e $apps_db_file ]]; then
-        echo -e "\n${F_SCR}${F_WAR}No db file found.$NS"
+        non_gui_message "\n${F_SCR}${F_WAR}No db file found.$NS"
         return
     fi
-    echo -e "$F_OK"
+    non_gui_message "$F_OK"
 
     # Get apps_db_file content into an array
     mapfile -t apps_db < <(cat "$apps_db_file")
@@ -252,7 +353,7 @@ function get_dir_and_files_from_db()
     done
 
     if [[ ${#app_dirs_and_files[@]} -eq 0 ]]; then
-        echo -e "${F_SCR}${F_WAR}No data found.$NS"
+        non_gui_message "${F_SCR}${F_WAR}No data found.$NS"
     elif [[ ${app_dirs_and_files[0]} == "FAKEHOME" ]]; then
         fake_home_mode=true
     fi
@@ -270,15 +371,15 @@ function get_dir_and_files_from_db()
 #===============================================================================
 function get_home_diff_list()
 {
-    echo -en "${F_SCR}${ITL}Getting hidden dirs/files created in HOME...$NS "
+    partial_msg "${F_SCR}${ITL}Getting hidden dirs/files created in HOME...$NS "
 
     local differences=""
     # Get only diff entries between home_before and home_after
     differences=$(diff --changed-group-format='%>' --unchanged-group-format=''\
                   <(echo -e "$home_before") <(echo -e "$home_after") || true)
     if [[ -z "$differences" ]]; then
-        echo -e "\n$F_SCR${ITL}No new dirs or files detected. Nothing to do."
-        echo -e "$F_SCR${ITL}Closing...$NS"
+        partial_msg "\n$F_SCR${ITL}No new dirs or files detected. Nothing to do.$NS"
+        notify_msg "\n$F_SCR${ITL}Closing...$NS"
         exit
     fi
 
@@ -289,12 +390,12 @@ function get_home_diff_list()
     # Convert into an array
     mapfile -t app_dirs_and_files <<< "$differences"
 
-    echo -e "$F_OK"
-    echo -en "${F_SCR}${ITL}Obtained elements: $NS"
+    non_gui_message "$F_OK"
+    partial_msg "${F_SCR}${ITL}Obtained elements: $NS"
     for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
-        echo -en "${BLD}'${app_dirs_and_files[i]}' "
+        partial_msg "\n${BLD}'${app_dirs_and_files[i]}' "
     done
-    echo -e "$NS"
+    non_gui_message "$NS"
 
 }  # ------------  end of function get_home_diff_list  ------------
 
@@ -321,7 +422,6 @@ function interruption_handler()
     # For some reason when this function is called through trap, using the
     # separator function will end the script execution wihout running the next
     # lines of this function. So we need to duplicate some code from separator.
-    local sep_char="="
     local max_line_length=""
     if [[ -z $TERM || $TERM == "dumb" ]]; then
         max_line_length=1
@@ -330,22 +430,19 @@ function interruption_handler()
     fi
     local output=""
     for (( i=0; i<max_line_length; i++ )); do
-        output="${output}${sep_char}"
+        output="${output}${F_SEP}"
     done
-    echo -e "\n${GREEN}${output}${NS}"
+    non_gui_message "\n${GREEN}${output}${NS}"
 
-    echo -e "$F_SCR${F_ERR}Exiting on signal SIGINT:" \
-            "'${F_APP}${F_ERR}' terminated.$NS"
+    partial_msg "Exiting on signal SIGINT: '${F_APP}' terminated.$NS"
 
     if [[ $fake_home_mode == false ]]; then
         mv_dirs_and_files_from_home
     fi
-    echo -e "$F_SCR${ITL}Closing...$NS"
+    notify_msg "$F_SCR${ITL}Closing...$NS"
     exit
 
 }  # ------------  end of function interruption_handler  ------------
-
-
 
 
 
@@ -356,10 +453,10 @@ function interruption_handler()
 function make_data_folder()
 {
     if [[ ! -d "$FORCE_XDG_FOLDER" ]]; then
-        echo -en "${F_SCR}Creating"\
+        partial_msg "${F_SCR}Creating"\
                  "'$ORANGE$FORCE_XDG_FOLDER$NS$ITL' folder... "
         mkdir -p "$FORCE_XDG_FOLDER"
-        echo -e "$F_OK"
+        notify_msg "$F_OK"
     fi
 
 }  # ------------  end of function make_data_folder  ------------
@@ -372,10 +469,10 @@ function make_data_folder()
 #===============================================================================
 function mv_dirs_and_files_from_home()
 {
-    echo -en "${F_SCR}${ITL}Cleaning home...$NS "
+    partial_msg "${F_SCR}${ITL}Cleaning home...$NS "
     # Create dir if doesn't exists
     if [[ ! -d "${FORCE_XDG_FOLDER}/${app_name}" ]]; then
-        echo -en "\n${F_SCR}${ITL}and creating target folder: '$F_APP'$NS "
+        partial_msg "\n${F_SCR}${ITL}and creating target folder: '$F_APP'...$NS "
         mkdir "${FORCE_XDG_FOLDER}/${app_name}"
     fi
 
@@ -384,7 +481,7 @@ function mv_dirs_and_files_from_home()
         local file=${app_dirs_and_files[i]}
         mv "$HOME/.$file" "${FORCE_XDG_FOLDER}/$app_name/$file"
     done
-    echo -e "$F_OK"
+    notify_msg_dont_store "$F_OK"
 
 }  # ------------  end of function mv_dirs_and_files_from_home  ------------
 
@@ -396,13 +493,13 @@ function mv_dirs_and_files_from_home()
 #===============================================================================
 function mv_dirs_and_files_to_home()
 {
-    echo -en "${F_SCR}${ITL}Moving '${F_APP}' folders to home..."
+    non_gui_message "${F_SCR}${ITL}Moving '${F_APP}' folders to home..."
     # First check if any folder/file already exist to prevent data loss
     for (( i=0; i<${#app_dirs_and_files[@]}; i++ )); do
         local file=${app_dirs_and_files[i]}
         if [[ -e "${HOME}/.${file}" ]]; then
-            echo -e "\n$F_ERR${SCRIPT_RUN}:$NS ${F_ERR}Error: '$file'"\
-                    "already exist in home folder.$NS" >&2
+            error_msg "Unable to move '$file' to home" \
+                "because it already exists.$NS"
             exit 1
         fi
     done
@@ -411,7 +508,7 @@ function mv_dirs_and_files_to_home()
         local file=${app_dirs_and_files[i]}
         mv "${FORCE_XDG_FOLDER}/${app_name}/${file}" "${HOME}/.${file}"
     done
-    echo -e " $F_OK"
+    non_gui_message " $F_OK"
 
 }  # ------------  end of function mv_dirs_and_files_to_home  ------------
 
@@ -428,13 +525,13 @@ function run_app()
     else
         app_command="${ORANGE}${app_name_raw} ${app_args}${NS}${ITL}"
     fi
-    echo -e "${F_SCR}${ITL}Running '${app_command}':$NS"
+    non_gui_message "${F_SCR}${ITL}Running '${app_command}':$NS"
     separator "${app_name}"
 
     eval " $app_name_raw $app_args"
 
     separator
-    echo -e "${F_SCR}${ITL}Closed '${F_APP}'$NS"
+    non_gui_message -e "${F_SCR}${ITL}Closed '${F_APP}'$NS"
 
 }  # ------------  end of function run_app  ------------
 
@@ -446,11 +543,11 @@ function run_app()
 #===============================================================================
 function save_app_info_into_db()
 {
-    echo -e "${F_SCR}${ITL}Storing '${F_APP}' info in the database:$NS"
+    non_gui_message "${F_SCR}${ITL}Storing '${F_APP}' info in the database:$NS"
     if [[ ! -f $apps_db_file ]]; then
-        echo -en "${F_SCR}${ITL}Creating the database file... "
+        partial_msg "${F_SCR}${ITL}Creating the database file... "
     else
-        echo -en "${F_SCR}${ITL}Updating the database... "
+        partial_msg "${F_SCR}${ITL}Updating the database... "
     fi
 
     local data="$app_name"
@@ -465,7 +562,7 @@ function save_app_info_into_db()
 
     echo "$data" >> "$apps_db_file"
     sort -o "$apps_db_file" "$apps_db_file"
-    echo -e "$F_OK"
+    non_gui_message "$F_OK"
 
 }  # ------------  end of function save_app_info_into_db  ------------
 
@@ -479,7 +576,10 @@ function save_app_info_into_db()
 #===============================================================================
 function separator()
 {
-    local sep_char="="
+    if [[ $kde_mode == true ]]; then
+        return
+    fi
+
     local max_line_length=""
     # Fix KDE error: <tput: No value for $TERM and no -T specified>
     if [[ -z $TERM || $TERM == "dumb" ]]; then
@@ -492,7 +592,7 @@ function separator()
     # If no arg, then draw a separation line without text
     if [[ $# -eq 0 ]]; then
         for (( i=0; i<max_line_length; i++ )); do
-            output="${output}${sep_char}"
+            output="${output}${F_SEP}"
         done
         echo -e "${GREEN}${output}${NS}"
         return
@@ -501,7 +601,7 @@ function separator()
     #----------------------------------------
     # Build the separator with the argument
     local text="${1^}"
-    local out_beginning="${sep_char}${sep_char}${sep_char} "
+    local out_beginning="${F_SEP}${F_SEP}${F_SEP} "
     local out_middle="${text} Output: "
     local out_current_length=$((${#out_beginning} + ${#out_middle}))
     local remaining_length=$((max_line_length - out_current_length))
@@ -516,7 +616,7 @@ function separator()
     # Get the separator horizontal line with the corresponding remaining length
     local out_end=""
     for (( i=0; i<remaining_length; i++ )); do
-        out_end="${out_end}${sep_char}"
+        out_end="${out_end}${F_SEP}"
     done
 
     # Finally the string can be built
@@ -543,13 +643,13 @@ get_dir_and_files_from_db
 # Fake Home Mode
 #-------------------------------------------------------------------------------
 if [[ $fake_home_mode == true ]]; then
-    echo -e "${F_SCR}${ITL}Running in fake home mode...$NS"
+    non_gui_message "${F_SCR}${ITL}Running in fake home mode...$NS"
     FORCE_XDG_FOLDER="${FAKE_HOME_FOLDER}"
     HOME="${FAKE_HOME_FOLDER}"
 
-    echo -e "${F_SCR}${ITL}Fake home setted to ${NS}${ORANGE}'${HOME}'$NS"
+    non_gui_message "${F_SCR}${ITL}Fake home setted to ${NS}${ORANGE}'${HOME}'$NS"
     if [[ ! -d $HOME ]]; then
-        echo -e "${F_SCR}${ITL}${ORANGE}Fake home directory not found.$NS"
+        non_gui_message "${F_SCR}${ITL}${ORANGE}Fake home directory not found.$NS"
         make_data_folder
     fi
     trap "interruption_handler" INT
@@ -559,7 +659,7 @@ if [[ $fake_home_mode == true ]]; then
     if [[ ${#app_dirs_and_files[@]} -eq 0 ]]; then
         save_app_info_into_db
     fi
-    echo -e "$F_SCR${ITL}Closing...$NS"
+    non_gui_message "$F_SCR${ITL}Closing...$NS"
     exit
 fi
 
@@ -589,6 +689,6 @@ fi
 # Cleaning home
 
 mv_dirs_and_files_from_home
-echo -e "$F_SCR${ITL}Closing...$NS"
+non_gui_message "$F_SCR${ITL}Closing...$NS"
 exit
 
